import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';

const NAV=['Research Agent','Data Import','Product Detail','Profit Calculator','Settings'];
const SAMPLE=[
{id:'s1',title:'Portable Bluetooth Speaker with RGB Light',category:'Speakers',price:699,rating:4.4,reviews:18420,sellerCount:38,sales:12600,image:'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=640&q=80'},
{id:'s2',title:'Mini Wireless Bluetooth Speaker',category:'Speakers',price:399,rating:4.2,reviews:11250,sellerCount:55,sales:9600,image:'https://images.unsplash.com/photo-1589256469067-ea99122bbdc1?auto=format&fit=crop&w=640&q=80'},
{id:'s3',title:'Bass Boost Bluetooth Speaker',category:'Speakers',price:899,rating:4.6,reviews:8400,sellerCount:21,sales:7200,image:'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=640&q=80'},
{id:'s4',title:'Pocket Bluetooth Speaker',category:'Speakers',price:549,rating:4.3,reviews:5400,sellerCount:44,sales:4100,image:'https://images.unsplash.com/photo-1602874801006-a3f85bbf7aaf?auto=format&fit=crop&w=640&q=80'}
];
const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
const num=v=>Number(String(v??'').replace(/[^0-9.-]/g,''))||0;
const clamp=(v,a=0,b=100)=>Math.min(b,Math.max(a,v));
const uid=()=>Math.random().toString(36).slice(2,9)+Date.now().toString(36);

function normalizeRow(row,i){
 const get=(...keys)=>{for(const k of keys){const f=Object.keys(row).find(x=>x.toLowerCase().replace(/[^a-z0-9]/g,'')===k.toLowerCase().replace(/[^a-z0-9]/g,''));if(f&&row[f]!=='')return row[f]}return''};
 return {id:String(get('id','product_id')||`p${i+1}-${uid()}`),title:String(get('title','product','product_name','name','listing_title')||'Unknown product'),category:String(get('category','subcategory')||'Uncategorized'),price:num(get('price','selling_price','sale_price','current_price')),cost:num(get('cost','product_cost','purchase_cost')),rating:num(get('rating','star_rating')),reviews:num(get('reviews','review_count','rating_count','ratings')),sellerCount:num(get('seller_count','sellers','competition','competitor_count')),sales:num(get('sales','units_sold','sold','orders','order_count')),image:String(get('image','image_url','product_image','thumbnail')||''),url:String(get('url','product_url','link')||'')};
}
function parseCSV(text){const lines=text.split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const line=p=>{const o=[];let c='',q=false;for(let i=0;i<p.length;i++){const x=p[i];if(x==='"'&&p[i+1]==='"'){c+='"';i++;continue}if(x==='"'){q=!q;continue}if(x===','&&!q){o.push(c.trim());c=''}else c+=x}o.push(c.trim());return o};const h=line(lines[0]);return lines.slice(1).map(r=>{const v=line(r),o={};h.forEach((k,i)=>o[k]=v[i]??'');return o})}
function parseInput(text,type){try{if(type==='json'||text.trim().startsWith('[')||text.trim().startsWith('{')){const raw=JSON.parse(text);const arr=Array.isArray(raw)?raw:(raw.products||raw.items||raw.data||[]);return arr.map(normalizeRow)}return parseCSV(text).map(normalizeRow)}catch{return[]}}
function rank(rows,targetMargin,maxPrice){if(!rows.length)return[];const ms=Math.max(...rows.map(r=>r.sales),1),mr=Math.max(...rows.map(r=>r.reviews),1),mse=Math.max(...rows.map(r=>r.sellerCount),1);return rows.map(r=>{const demand=clamp((r.sales>0?r.sales/ms:r.reviews/mr)*100),rating=clamp(r.rating/5*100),review=clamp(Math.log10(r.reviews+1)/Math.log10(mr+1)*100),competition=r.sellerCount?clamp(100-r.sellerCount/mse*100):55,margin=r.cost&&r.price?clamp((r.price-r.cost)/r.price*100):45,priceFit=maxPrice?clamp(150-r.price/maxPrice*100):70,op=clamp(demand*.35+rating*.15+review*.15+competition*.15+clamp(margin/Math.max(targetMargin,1)*100)*.15+priceFit*.05);return{...r,demandScore:Math.round(demand),competitionScore:Math.round(competition),margin:Math.round(margin),opportunity:Math.round(op),verdict:op>=78?'TEST NOW':op>=62?'WATCH':'AVOID'}}).sort((a,b)=>b.opportunity-a.opportunity)}

function App(){const[page,setPage]=useState('Research Agent'),[rows,setRows]=useState(SAMPLE),[query,setQuery]=useState('speaker'),[tm,setTm]=useState(30),[mp,setMp]=useState(1500),[selected,setSelected]=useState(null),[toast,setToast]=useState('');const results=useMemo(()=>rank(rows.filter(r=>!query||r.title.toLowerCase().includes(query.toLowerCase())||r.category.toLowerCase().includes(query.toLowerCase())),tm,mp),[rows,query,tm,mp]);const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2200)};return <div className="app"><aside><div className="brand"><div className="brand-mark">M</div><div><b>Meesho AI</b><span>Product Research Agent</span></div></div><nav>{NAV.map(n=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><span className="nav-icon">{{'Research Agent':'⌕','Data Import':'⇪','Product Detail':'◈','Profit Calculator':'₹','Settings':'⚙'}[n]}</span>{n}</button>)}</nav><div className="side-note"><b>Private research</b><p>Use a CSV/JSON dataset you are allowed to collect. Sales, reviews and competition are shown exactly as supplied.</p></div></aside><main><header><div><div className="eyebrow">PRODUCT RESEARCH AI</div><h1>{page}</h1><p>Find promising products from your supplied marketplace dataset.</p></div><div className="top-pill">{rows.length} products</div></header>{page==='Research Agent'&&<Research rows={results} q={query} setQ={setQuery} tm={tm} setTm={setTm} mp={mp} setMp={setMp} select={r=>{setSelected(r);setPage('Product Detail')}}/>}{page==='Data Import'&&<Import rows={rows} setRows={setRows} notify={notify}/>} {page==='Product Detail'&&<Detail product={selected||results[0]} back={()=>setPage('Research Agent')}/>} {page==='Profit Calculator'&&<Profit rows={rows}/>} {page==='Settings'&&<Settings/>}</main>{toast&&<div className="toast">✓ {toast}</div>}</div>}
function Research({rows,q,setQ,tm,setTm,mp,setMp,select}){const sales=rows.some(r=>r.sales>0),top=rows[0],avgR=rows.length?rows.reduce((a,r)=>a+r.rating,0)/rows.length:0,avgP=rows.length?rows.reduce((a,r)=>a+r.price,0)/rows.length:0;return <section className="page"><div className="hero"><div><span className="eyebrow">WINNING PRODUCT FINDER</span><h2>Search a product. Get a decision.</h2><p>Rankings use sales when present; otherwise reviews are clearly treated as a demand proxy.</p></div><div className="hero-result">{top?<><span>Top opportunity</span><b>{top.title}</b><strong>{top.opportunity}/100</strong></>:<span>No matches</span>}</div></div><div className="controls panel"><div className="search-wrap"><label>Product / category<input value={q} onChange={e=>setQ(e.target.value)} placeholder="speaker"/></label><label>Target margin %<input type="number" value={tm} onChange={e=>setTm(num(e.target.value))}/></label><label>Max price<input type="number" value={mp} onChange={e=>setMp(num(e.target.value))}/></label></div></div><div className="stats"><Stat l="Listings analyzed" v={rows.length}/><Stat l={sales?'Top units sold':'Top demand proxy'} v={sales?Math.max(...rows.map(r=>r.sales),0).toLocaleString('en-IN'):(rows[0]?.reviews||0).toLocaleString('en-IN')}/><Stat l="Avg rating" v={avgR?avgR.toFixed(2):'—'}/><Stat l="Avg price" v={money(avgP)}/></div><div className="panel"><div className="panel-head"><div><h3>Ranked listings</h3><p>{sales?'Actual sales field detected.':'No sales field found; reviews are used as a proxy.'}</p></div></div><div className="table"><div className="tr head"><span>Product</span><span>Price</span><span>Rating</span><span>Reviews</span><span>Competition</span><span>Score</span><span>Decision</span></div>{rows.map(r=><button className="tr body" key={r.id} onClick={()=>select(r)}><span className="product-cell"><img src={r.image||'https://dummyimage.com/64x64/e5e7eb/6b7280&text=No+Image'} alt=""/><span><b>{r.title}</b><small>{r.category}</small></span></span><span>{money(r.price)}</span><span>{r.rating?`${r.rating.toFixed(1)} ★`:'—'}</span><span>{r.reviews?r.reviews.toLocaleString('en-IN'):'—'}</span><span>{r.sellerCount?r.sellerCount+' sellers':'Unknown'}</span><span><b className="score">{r.opportunity}</b></span><span><b className={`verdict ${r.verdict.toLowerCase().replace(/\s/g,'-')}`}>{r.verdict}</b></span></button>)}</div></div></section>}
function Import({rows,setRows,notify}){const[text,setText]=useState(''),[fileName,setFileName]=useState('');const apply=t=>{const parsed=parseInput(t,t.trim().startsWith('{')||t.trim().startsWith('[')?'json':'csv');if(!parsed.length)return notify('No valid products found.');setRows(parsed);notify(`${parsed.length} products imported.`)};const onFile=async e=>{const f=e.target.files?.[0];if(!f)return;setFileName(f.name);const t=await f.text();setText(t);apply(t)};return <section className="page"><div className="two-col"><div className="panel"><h2>Import your research data</h2><p>CSV or JSON from an allowed/authorized source.</p><label className="upload"><input type="file" accept=".csv,.json,text/csv,application/json" onChange={onFile}/><b>Choose CSV / JSON</b><span>{fileName||'No file selected'}</span></label><button className="secondary full" onClick={()=>{setRows(SAMPLE);notify('Speaker demo loaded.')}}>Load speaker demo</button></div><div className="panel"><h3>Paste data</h3><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={'title,price,rating,reviews,seller_count,sales,image_url\nPortable Speaker,699,4.4,18420,38,12600,https://...'}/><button className="primary full" onClick={()=>apply(text)}>Analyze data</button><div className="schema"><b>Recommended columns</b><span>title, price, rating, reviews, seller_count, sales, image_url, product_url, cost</span></div></div></div><div className="panel"><h3>Loaded listings</h3>{rows.slice(0,10).map(r=><div className="mini-row" key={r.id}><b>{r.title}</b><span>{money(r.price)} · {r.rating||'—'}★ · {(r.reviews||0).toLocaleString('en-IN')} reviews</span></div>)}</div></section>}
function Detail({product,back}){if(!product)return <section className="page"><div className="panel"><h2>No product selected</h2><button className="primary" onClick={back}>Back</button></div></section>;return <section className="page"><button className="ghost" onClick={back}>← Back</button><div className="detail-grid"><div className="panel"><img className="detail-image" src={product.image||'https://dummyimage.com/640x480/e5e7eb/6b7280&text=No+Image'} alt={product.title}/>{product.url?<a href={product.url} target="_blank" rel="noreferrer">Open source listing →</a>:<span className="muted">Source URL not supplied</span>}</div><div className="panel"><span className={`verdict big ${product.verdict?.toLowerCase().replace(/\s/g,'-')||''}`}>{product.verdict||'UNRANKED'}</span><h2>{product.title}</h2><p>{product.category}</p><div className="detail-stats"><Metric l="Opportunity" v={`${product.opportunity??0}/100`}/><Metric l="Price" v={money(product.price)}/><Metric l="Rating" v={product.rating?`${product.rating.toFixed(1)} ★`:'—'}/><Metric l="Reviews" v={product.reviews?product.reviews.toLocaleString('en-IN'):'—'}/><Metric l="Competition" v={product.sellerCount?`${product.sellerCount} sellers`:'Unknown'}/><Metric l="Sales" v={product.sales?product.sales.toLocaleString('en-IN')+' units':'Not supplied'}/></div><div className="advice"><b>Why this scored here</b><p>Demand {product.demandScore}/100 · Competition {product.competitionScore}/100 · Modeled margin {product.margin}%. Use this as a research signal, not a sales guarantee.</p></div></div></div></section>}
function Metric({l,v}){return <div><span>{l}</span><b>{v}</b></div>}
function Profit({rows}){const[cost,setCost]=useState(120),[ship,setShip]=useState(40),[fee,setFee]=useState(12),[price,setPrice]=useState(rows[0]?.price||699);const total=cost+ship+price*fee/100,profit=price-total,margin=price?profit/price*100:0;return <section className="page two-col"><div className="panel"><h2>Profit Calculator</h2>{[['Product cost',cost,setCost],['Shipping',ship,setShip],['Platform fee %',fee,setFee],['Selling price',price,setPrice]].map(([l,v,s])=><label key={l}>{l}<input type="number" min="0" value={v} onChange={e=>s(num(e.target.value))}/></label>)}</div><div className="panel result-panel"><Metric l="Total cost" v={money(total)}/><Metric l="Profit" v={money(profit)}/><Metric l="Margin" v={`${margin.toFixed(1)}%`}/><div className="advice"><b>Decision</b><p>Compare this margin with your top-ranked product before ordering stock.</p></div></div></section>}
function Settings(){return <section className="page two-col"><div className="panel"><h2>Settings</h2><label>Currency<select><option>INR ₹</option></select></label><label>Target margin %<input type="number" defaultValue="30"/></label><label>Max price<input type="number" defaultValue="1500"/></label></div><div className="panel"><h3>Truth rules</h3><div className="check">✓ Sales ranking uses actual sales when supplied.</div><div className="check">✓ Reviews become the demand proxy only when sales are missing.</div><div className="check">✓ Competition uses seller count when supplied.</div><div className="check">✓ The recommendation is a research signal, not a guarantee.</div></div></section>}
function Stat({l,v}){return <div className="stat-card"><span>{l}</span><b>{v}</b></div>}
createRoot(document.getElementById('root')).render(<App/>);
